import localFont from "next/font/local";
import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar";
import { ThemeProvider } from "@mui/material/styles";
import theme from './theme'
import Footer from "./_Components/Footer";

const figtree = Figtree({
  display: "swap",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-figtree",
});

export const champagneLimousines = localFont({
  src: [
    {
      path: "../../public/fonts/ttf/champagne-limousines-bold-italic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/ttf/champagne-limousines-bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/ttf/champagne-limousines-italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/ttf/champagne-limousines.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-champagne-limousines",
});

export const kalameh = localFont({
  src: [
    // Regular Kalameh fonts
    {
      path: "../../public/fonts/woff2/kalamehweb-thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehweb-extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehweb-light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehweb-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehweb-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehweb-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehweb-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehweb-extrabold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehweb-black.woff2",
      weight: "900",
      style: "normal",
    },

    // Kalameh with Farsi Numerals (FaNum)
    {
      path: "../../public/fonts/woff2/kalamehwebfanum-thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebfanum-extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebfanum-light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebfanum-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebfanum-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebfanum-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebfanum-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebfanum-extrabold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebfanum-black.woff2",
      weight: "900",
      style: "normal",
    },

    // Kalameh No English (NoEn)
    {
      path: "../../public/fonts/woff2/kalamehwebnoen-thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebnoen-extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebnoen-light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebnoen-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/kalamehwebnoen-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebnoen-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebnoen-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebnoen-extrabold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/woff2/Kalamehwebnoen-black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-kalameh",
});

export const metadata = {
  title: "Artemist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`dark ${figtree.variable} ${champagneLimousines.variable}`}>
      <body>
      <ThemeProvider theme={theme}>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
